workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Clean previous builds and pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod cache clean --all
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Set up temporary .env file for build
        script: |
          echo "API_KEY=${API_KEY}" > .env
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa

ios:
  xcode_workspace: "ios/Runner.xcworkspace"
  xcode_scheme: "Runner"
  build_settings:
    ENABLE_BITCODE: NO
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES: YES
    IPHONEOS_DEPLOYMENT_TARGET: "13.0"
